import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import HeaderSidebar from "@/components/header-sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AplicacionLayout({ children }) {
  return (
    <SidebarProvider>
      <AppSidebar/>
      <SidebarInset>
        <HeaderSidebar />
        <div className="p-4">
          <div className="flex flex-col gap-4">
            {children}
          </div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
